apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-pv
  labels: 
    storage: lento
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /mnt/data
  storageClassName: giropops

