apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name:  nginx-persistent-storage
spec: 
  accessModes: 
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 1Gi 
  storageClassName: giropops 
  selector: 
    matchLabels: 
      storage: giropops
