apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  selector:
    app: giropops-senhas
  ports:
  - port: 8888
    name: giropops-senhas
    targetPort: 8888
  type: ClusterIP

