apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas-nodeport
  labels:
    app: giropops-senhas
spec:
  selector:
    app: giropops-senhas
  ports:
  - port: 8888
    name: giropops-port
    targetPort: 8888
  externalIPs:
    - 100.25.3.231
    - 54.236.54.171
  type: NodePort

