apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-3
  labels:
    app: redis
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
  storageClassName: giropops

