apiVersion: v1
kind: Service
metadata:
  name: redis-headless-svc
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports: 
  - port: 6379
    name: redis
    targetPort: 6379
  clusterIP: None

