apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: developer
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dUQ0NBVUVDQVFBd0ZERVNNQkFHQTFVRUF3d0paR1YyWld4dmNHVnlNSUlCSWpBTkJna3Foa2lHOXcwQgpBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0SDlyRGdhUVpwdFllYXNlNE9PMW9XakNuK05rNVBid3dVdmNTS1drCmNodkg2WkdHWC90VjZ6VTBCeFplZlJ4Qmpha24yZUQ4b1pwSTVPNFZTenZzVFJVeUhtUFZNNVZ4Uy8yTkIwRFYKeEJmS0MvQldFK3BNR3U5eWpuUlViYithaXdpaWJ0WHQrOXRzR015cThYb2hBWlZmNFNoRGo1enRpQU11amVKWQpKZWpPMjE5ODl2dUtObk5ZcEU3bDVySXRzVlB2cE1ER0ZrRFhvamcwSUx0MmlHanAxRWN5c2oxSUd3RUZqVU9EClRUdVF4cjdwbTJpVXpRMXFvZHhhUTVaVklRWXV3NC83TVlmWHhXNmxGZWNxYXVidXdoZWhGV1daL1dmeXJzblQKc2FPOHdBZ2FwWmZpV0FRK0dCL1dKYjNSRlBBbGpsbGxxTkI4b0huSGdHSHF4d0lEQVFBQm9BQXdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUQ1OU41ZTlsNjNnOWtCN1ZWZ0Z6Wkg1elhuMmJucERjZm4rbmpaWXNBT1ljMVVjCmNkdnFrc25NM29YK0YwbkQ1b01KN1FHYk9FZ3pOeFJXOG5ONnU5TkhvV0VHVHh0Y3FLOU9FWHBtcU0zdkhqelkKZWZUejFYWjRwUmdJd2pMbmIxSmFVK0Z3aFdtbUo3eFlMTWRlNW02VE9VTjhRcGttcGQ0YkR0ODN5emVvNTVQbgp3QW54MHM5UmNDajBoQU1WaXRvSWhjNFE4RHQ3VnVOTUpyUWk2eUVpQkxvdlUrS2pOTnZqTTdBMTdJVy9pVnppClZ3Q3VRdUZnS1ZzZW5jRmxoVnY5V1hMSjVoWEZDM2FPUVIvNzNCVHVNYk5TSEJ5UGZnWmRjZ3NFTWIrc1ExZW4KNENNdWgzNkRld2lOSzFodGpsVzFVZXVydE84WVNjN1RuakhJOHRRPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 31536000
  usages:
  - client auth


