apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-leitor
roleRef: 
  kind: Role
  name: sa-role
  apiGroup: rbac.authorization.k8s.io

