apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemonitor
  labels:
    app: nginx
spec:
  selector:
    matchLabels: 
      app: nginx
  endpoints:
    - interval: 30s
      path: /metrics
      targetPort: 9113
