apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: webeserver
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-emptydir
    resources: 
      limits:
        cpu: "1.0"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 256Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
